services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - UID=${UID}
      - GID=${GID}
    volumes:
      - .:/sample-app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db-data: